extra_prepare_dict:
    extra_qconfig_dict:
        w_observer: MinMaxObserver
        a_observer: EMAMSEObserver
        w_fakequantize: LearnableFakeQuantize
        a_fakequantize: LearnableFakeQuantize
        w_qscheme:
            bit: 4
            symmetry: True
            sign: True  # MQB就缺个这个，整蒙了
            per_channel: False
            pot_scale: False
        a_qscheme:
            bit: 4
            symmetry: True
            sign: False  # MQB就缺个这个，整蒙了
            per_channel: False
            pot_scale: False

quantize:
    quantize_type: naive_ptq # support naive_ptq or advanced_ptq
    cali_batchnum: 256  # 越多越好？？似乎是的
    quant_algorithm: lsq

training:
    my_buff_flag: 2
    qloss_flag: False
    pretrained_flag: True
    fold_bn_flag: False
misc:
    resume: False

